# fly.toml app configuration file generated for hello-fly-sparkling-sound-4361 on 2025-07-10T14:56:58-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lbr-test'
primary_region = 'dfw'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[experimental]
  auto_rollback = true


[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
